server:
  port: 9999

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: update
      use_sql_comments: true # View JPQL Query


logging:
  level:
    org.hibernate.SQL: debug
